### ISSUE TITLE
Support multiple GPUs

### ISSUE THREAD

**Issue by tazlin** [Haidra-Org/hordelib_old#123]
Mutli-threading, especially in the context of multiple GPUS, may have some benefits to the workers who have setups that can support it.

Protentional roadblocks include:

- #122 
- #56 
- ...

**Comment by jug-dev** [comment]
It's worth noting it has been observed that a hordelib based worker supports running multiple instances, each on a different GPU, out of the box. Some worker operators have done this, without changing the config or having multiple copies of the worker folder.

Multi-threading is supported.

I suggest the existing functionality constitutes multi-GPU support, or as close as we're going to get, and I recommend closing this issue lest it become one of those issues that simply sits open for years.
