### ISSUE TITLE
Support LORA

### ISSUE THREAD

**Issue by tazlin** [Haidra-Org/hordelib_old#124]
We need to:

- [x] Have a mechanism for specifying an arbitrary number of LORAs plus model weight and clip weight for each to the library.  For example:
 - An explicit data structure (e.g. {"wethair":{"model": 0.4, "clip": 1.0}} )
 - ~~An implicit parsing of the prompt. If I have "wethair" in my prompt and there is a "wethair" lora, use that. Gives rise to (wethair:0.4) to also set both weights.~~
- [x] Support dynamic injection of nodes into the graph and chaining these nodes together and connecting the last one with the CLIP text encoders and sampler.
- [x] ~~Support loading these LORA models with a horde custom node (which will later be connected to the model manager in some way)~~ Not required.
- [x] Support patching the model without leaking into other threads (like controlnet).
- [ ] Add support for all relevant pipelines, and exclude those that aren't relevant. 

We may need:

- [x] To replace the current controlnet solution (copying models) with a mechanism that allows the model to be "checked out" of the model manager exclusively and use this for LORAs also. This would drastically reduce memory usage of controlnet and LORAs.

See the [parent project](https://github.com/orgs/Haidra-Org/projects/3) for more info:

**Comment by jug-dev** [comment]
It's fully supported in the comfyui engine, just need the logistics of downloading the loras, etc. 

"etc" is doing a lot of work in that sentence.

**Comment by db0** [comment]
I thought the simplest solution was to just download all known ones at the get-go, assuming the worker says they want to support them? All together won't be much more than a couple of models no?

Then it's just a matter of the horde denying unknown LoRa names, and then adjusting the payload to send them

Do they have to be part of the prompt, or just an extra key in the payload? If the latter, a simple structure would be

```
"loras": [
   {
   "name": "lora1",
   "model": 0.4,
   "clip": 0.5,
   },
   {...
   }
]
```

**Comment by jug-dev** [comment]
_"I thought the simplest solution was to just download all known ones at the get-go, assuming the worker says they want to support them? All together won't be much more than a couple of models no?"_

I agree with just downloading them all if enabled by the worker. The typica LORA size is 77MB or 144MB. So 500 of those is going to be around 70GB.

_"Do they have to be part of the prompt, or just an extra key in the payload? If the latter, a simple structure would be"_

Both of these options are in the original ticket. I may just add both to hordelib and the caller can decide which way to go, be it the horde or another library user. I'll default to the explicit JSON specification of which LORAs to apply. The LORAs activation keywords still need to be in the prompt in any case.

**Comment by db0** [comment]
Hm, about the same size as 30 models. Not insignificant but should be doable with most SDD on the market nowadays. However I'm not sure if we strictly need ALL of them. A lot of them are probably garbage nobody uses. Does it makes sense to maintain our own list like we do for models to keep things manageable?

**Comment by db0** [comment]
Another idea, have an optional switch for workers for "download_unknown_loras" or something. When set, when the client sends an unknown LoRA, we redirect them to one of those workers, who will download it ad-hoc if they don't have it and serve it. Workers with fast internet and big SDDs can then switch that on to serve everything.

**Comment by jug-dev** [comment]
I was just speculating with that guess of 500 LORAs. I did a quick check of civitai and it's in the thouands.

**Comment by db0** [comment]
ok, then we need to fall back to an top X + adhoc + cache solution. I elaborated in the channel
