### ISSUE TITLE
n_iter values greater than one are not using default comfy optimizations

### ISSUE THREAD

**Issue by tazlin** [Haidra-Org/hordelib_old#225]
A temporary hack in `model_management.py` (func `maximum_batch_area`) is disabling some optimizations that may improve performance for high values of n_iter on higher end cards.

**Comment by jug-dev** [comment]
Removed temporary hack, added option to enable/disable batch optimisation, and controversially I'm sure, by default enabled batch optimisation.

**Comment by tazlin** [comment]
Re-opening to track progress.

**Comment by jug-dev** [comment]
Re-closing as I think we're done after this morning's measurements and comfyui upgrade.

**Comment by tazlin** [comment]
Issue appears to be resolved. Lesson learned - use better rulers. 

Results from `examples/run_long_prompt_check.py` are the best way to evaluate this issue for the time being.
