### ISSUE TITLE
Perform asserts on test-generated images for validation

### ISSUE THREAD

**Issue by db0** [Haidra-Org/hordelib_old#51]
There is a way to convert an image into tensors and then compare the tensors of two images to find their "distance". 

We could use this method to perform asserts on the image generated by our tests, by using deterministic generation parameters.

1. Generate the images locally, store the tensors in a file. 
2. During CI, load tensor data from disk
3. Generate test image and convert it to tensors
4. Compare distance between test image and control image. If distance over X, assert fails

**Comment by jug-dev** [comment]
Resolved by https://github.com/Haidra-Org/hordelib/pull/317
