### ISSUE TITLE
Be able to pre-load controlnet models in RAM

### ISSUE THREAD

**Issue by db0** [Haidra-Org/hordelib_old#56]
Currently we're sending the CN model path to `load_controlnet()` which then loads it into RAM and does the business.

To avoid wasting time. Add a way to pre-load the CNs into RAM, and then just pass the object. This might require patching `load_controlnet()` to make it accept an in-memory object instead.

**Comment by jug-dev** [comment]
load_controlnet() is patched by the comfy patcher to cache the files in ram
