### ISSUE TITLE
Can't distribute a worker as a zip file

### ISSUE THREAD

**Issue by jug-dev** [Haidra-Org/hordelib_old#69]
The current hordelib implementation would prevent the aihorde worker being distributed as a zip file, as hordelib itself currently requires a local git installation, and if someone is downloading zip releases they probably don't have git?

**Comment by db0** [comment]
Conda to the rescue! micromamba actually installs python and git!

![image](https://user-images.githubusercontent.com/296513/231155061-71c7d0a1-f3d9-4cc1-804e-21a22d45ad38.png)

**Comment by jug-dev** [comment]
great
