### ISSUE TITLE
Colab support; Colab is IPython 3.9

### ISSUE THREAD

**Issue by tazlin** [Haidra-Org/hordelib_old#72]
There appear to be workarounds for getting up to 3.10, but there's a bit of effort involved here. Hordelib as is using 3.10 specific syntax, and is not backwards compatible. A new notebook will need to be designed/worked on/supported.

**Comment by tazlin** [comment]
Google may be supporting 3.10 soon. This will become moot if/when that goes through.

**Comment by jug-dev** [comment]
Announcement issue is here: https://github.com/googlecolab/colabtools/issues/3572

**Comment by jug-dev** [comment]
<img width="354" alt="image" src="https://user-images.githubusercontent.com/124293863/235226781-7732c0f6-cf30-49a5-86d6-ac771002d447.png">
